"""Initial migration

Revision ID: f510d820d6a0
Revises: 
Create Date: 2025-05-03 08:37:59.413028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f510d820d6a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_chat_history', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='user或ai',
               existing_nullable=True)
        batch_op.alter_column('suggestions',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='建议的后续问题，JSON格式',
               existing_nullable=True)

    with op.batch_alter_table('ai_training_plans', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='计划持续时间（天）',
               existing_nullable=True)
        batch_op.alter_column('weekly_plan',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='周计划，JSON格式',
               existing_nullable=True)

    with op.batch_alter_table('challenge_participants', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='完成进度（百分比）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='帖子类型',
               existing_nullable=True)
        batch_op.alter_column('images',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='图片列表，JSON格式',
               existing_nullable=True)

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint('post_likes_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('post_likes_ibfk_2', type_='foreignkey')
        batch_op.drop_index('user_post_unique')
        batch_op.create_foreign_key('post_likes_ibfk_1', 'community_posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('post_likes_ibfk_2', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sport_challenges', schema=None) as batch_op:
        batch_op.alter_column('goal_type',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='目标类型',
               existing_nullable=True)
        batch_op.alter_column('goal_value',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='目标值',
               existing_nullable=True)
        batch_op.alter_column('reward_points',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='奖励积分',
               existing_nullable=True)
        batch_op.alter_column('reward_badge',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='奖励徽章',
               existing_nullable=True)

    with op.batch_alter_table('sport_goals', schema=None) as batch_op:
        batch_op.alter_column('daily_steps',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='每日步数目标',
               existing_nullable=True)
        batch_op.alter_column('daily_distance',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='每日距离目标（公里）',
               existing_nullable=True)
        batch_op.alter_column('daily_calories',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='每日消耗卡路里目标',
               existing_nullable=True)
        batch_op.alter_column('weekly_frequency',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='每周运动频次目标',
               existing_nullable=True)
        batch_op.alter_column('weekly_duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='每周运动时长目标（分钟）',
               existing_nullable=True)

    with op.batch_alter_table('sport_records', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='运动类型',
               existing_nullable=True)
        batch_op.alter_column('distance',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='运动距离（米）',
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='运动时长（秒）',
               existing_nullable=True)
        batch_op.alter_column('calories',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='消耗卡路里',
               existing_nullable=True)
        batch_op.alter_column('avg_pace',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='平均配速',
               existing_nullable=True)
        batch_op.alter_column('route',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='运动轨迹，JSON格式',
               existing_nullable=True)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('preference',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='运动偏好类型',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0-女，1-男',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('idx_username')
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('venue_reservations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='pending, confirmed, cancelled, completed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('venue_reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1-5星',
               existing_nullable=True)

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='多张图片，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('facilities',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='场地设施，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('rules',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='场地规则，JSON格式',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('rules',
               existing_type=mysql.TEXT(),
               comment='场地规则，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('facilities',
               existing_type=mysql.TEXT(),
               comment='场地设施，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('images',
               existing_type=mysql.TEXT(),
               comment='多张图片，JSON格式',
               existing_nullable=True)

    with op.batch_alter_table('venue_reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               comment='1-5星',
               existing_nullable=True)

    with op.batch_alter_table('venue_reservations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=16),
               comment='pending, confirmed, cancelled, completed',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('idx_username', ['username'], unique=False)
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               comment='0-女，1-男',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('preference',
               existing_type=mysql.VARCHAR(length=64),
               comment='运动偏好类型',
               existing_nullable=True)

    with op.batch_alter_table('sport_records', schema=None) as batch_op:
        batch_op.alter_column('route',
               existing_type=mysql.TEXT(),
               comment='运动轨迹，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('avg_pace',
               existing_type=mysql.VARCHAR(length=16),
               comment='平均配速',
               existing_nullable=True)
        batch_op.alter_column('calories',
               existing_type=mysql.FLOAT(),
               comment='消耗卡路里',
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               comment='运动时长（秒）',
               existing_nullable=True)
        batch_op.alter_column('distance',
               existing_type=mysql.FLOAT(),
               comment='运动距离（米）',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=32),
               comment='运动类型',
               existing_nullable=True)

    with op.batch_alter_table('sport_goals', schema=None) as batch_op:
        batch_op.alter_column('weekly_duration',
               existing_type=mysql.INTEGER(),
               comment='每周运动时长目标（分钟）',
               existing_nullable=True)
        batch_op.alter_column('weekly_frequency',
               existing_type=mysql.INTEGER(),
               comment='每周运动频次目标',
               existing_nullable=True)
        batch_op.alter_column('daily_calories',
               existing_type=mysql.FLOAT(),
               comment='每日消耗卡路里目标',
               existing_nullable=True)
        batch_op.alter_column('daily_distance',
               existing_type=mysql.FLOAT(),
               comment='每日距离目标（公里）',
               existing_nullable=True)
        batch_op.alter_column('daily_steps',
               existing_type=mysql.INTEGER(),
               comment='每日步数目标',
               existing_nullable=True)

    with op.batch_alter_table('sport_challenges', schema=None) as batch_op:
        batch_op.alter_column('reward_badge',
               existing_type=mysql.VARCHAR(length=32),
               comment='奖励徽章',
               existing_nullable=True)
        batch_op.alter_column('reward_points',
               existing_type=mysql.INTEGER(),
               comment='奖励积分',
               existing_nullable=True)
        batch_op.alter_column('goal_value',
               existing_type=mysql.FLOAT(),
               comment='目标值',
               existing_nullable=True)
        batch_op.alter_column('goal_type',
               existing_type=mysql.VARCHAR(length=32),
               comment='目标类型',
               existing_nullable=True)

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=mysql.TEXT(),
               comment='图片列表，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=32),
               comment='帖子类型',
               existing_nullable=True)

    with op.batch_alter_table('challenge_participants', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=mysql.FLOAT(),
               comment='完成进度（百分比）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('ai_training_plans', schema=None) as batch_op:
        batch_op.alter_column('weekly_plan',
               existing_type=mysql.TEXT(),
               comment='周计划，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               comment='计划持续时间（天）',
               existing_nullable=True)

    with op.batch_alter_table('ai_chat_history', schema=None) as batch_op:
        batch_op.alter_column('suggestions',
               existing_type=mysql.TEXT(),
               comment='建议的后续问题，JSON格式',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=16),
               comment='user或ai',
               existing_nullable=True)

    # ### end Alembic commands ###
